name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    uses: mattwilkinsonn/dev-shared/.github/workflows/rust-devenv-ci.yml@v1
    permissions:
      contents: read
      id-token: write # the Determinate Nix action needs OIDC
